Better error handling and logging

diff --git a/backup-functions b/backup-functions
--- a/backup-functions
+++ b/backup-functions
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Backup routines
-# 2018 (c) Alex Ivkin
+# 2020 (c) Alex Ivkin
 #
 # TODO remove hardcoded sudo's from some routines (analyze)
 #    Change references from BACKUPDESTDIR to REMOTEDEST for remote backups
@@ -37,20 +37,20 @@ initBackup() {
     if [[ $destURL == "rsync:"* ]]; then  # backing up to remote rsync - use ssh to do remote validation
         if [[ -z "$(/sbin/ip addr show $IF)" ]]; then
             echo "*** Misconfiguration: network interface $IF does not exist" | tee -a $log
-            echo $DATE 20 $backupset >> $STATUSLOG
+            echo "$DATE 20 $backupset - misconfiguration. Network interface $IF does not exists ">> $STATUSLOG
             return 50
         fi
         # security validation - check that the router MAC and the server IP match pre-recoded values over the allowed interface
         if [[ -z "$(/sbin/ip addr show $IF to $NETMASK)" ]]; then
-            echo "*** Wrong network: $IF is not on $NETMASK" | tee -a $log
-            echo $DATE 50 $backupset >> $STATUSLOG
+            echo "*** Disallowed network: $IF is not on $NETMASK" | tee -a $log
+            echo "$DATE 50 $backupset - disallowed network. $IF is not on $NETMASK" >> $STATUSLOG
             return 50
         fi
         # fill in the arp cache by pinging once
         ping -c 1 $ROUTERIP 1>/dev/null
         if [[ -z "$(arp -a $ROUTERIP | grep $ROUTERMAC)" ]]; then
             echo "*** Wrong network: $ROUTERIP router MAC is not $ROUTERMAC" | tee -a $log
-            echo $DATE 51 $backupset >> $STATUSLOG
+            echo "$DATE 51 $backupset - disallowed network. network: $ROUTERIP router MAC is not $ROUTERMAC" >> $STATUSLOG
             return 51
         fi
         # try the SSH port
@@ -58,7 +58,7 @@ initBackup() {
         nc -z -w 3 $SERVER 22
         if [[ $? -ne 0 ]]; then
             echo "*** Backup server not reachable." | tee -a $log
-            echo $DATE 52 $backupset >> $STATUSLOG
+            echo "$DATE 52 $backupset - can not reach $SERVER" >> $STATUSLOG
             return 52
         fi
         REMOTEDEST=$(ssh -n $SERVER "sed -ne 's/^BACKUPDESTDIR=\([^ ]*\).*/\1/p' $(dirname $STATUSLOG)/backup.config")
@@ -67,19 +67,19 @@ initBackup() {
             ssh -n $SERVER "grep -qs '$REMOTEDEST' /proc/mounts"
             if [[ $? -eq 1 ]]; then
                 echo "*** Backup disk $REMOTEDEST is not mounted. Exiting." | tee -a $log
-                echo $DATE 99 $backupset >> $STATUSLOG
+                echo "$DATE 99 $backupset - backup disk $REMOTEDEST is not mounted on $SERVER." >> $STATUSLOG
                 return 99
             fi
             # backupdestdir would not be defined when using rsync URL
             freespace=$(ssh -n $SERVER "df -m \"$REMOTEDEST\"" | awk "NR==2{print \$4}")
             if [[ $freespace -le $MINSPACE ]]; then
                 echo "*** Backup space is running short. Only $freespace MB left on $REMOTEDEST!. Exiting." | tee -a $log
-                echo $DATE 95 $backupset >> $STATUSLOG
+                echo "$DATE 95 $backupset - backup free space on $SERVER is under the allowed limit of $freespace MB" >> $STATUSLOG
                 return 95
             fi
         else
             echo "*** Can not query remote disk $REMOTEDEST for free space. Exiting." | tee -a $log
-            echo $DATE 53 $backupset >> $STATUSLOG
+            echo "$DATE 53 $backupset - can not check free space on the remote disk $REMOTEDEST on $SERVER" >> $STATUSLOG
             return 53
         fi
         BACKUPDESTDIR=$REMOTEDEST # define BACKUPDESTDIR so that remote backups work.
@@ -87,13 +87,13 @@ initBackup() {
         grep -qs "$BACKUPDESTDIR" /proc/mounts
         if [[ $? -eq 1 ]]; then
             echo "*** Backup disk $BACKUPDESTDIR is not mounted. Exiting." | tee -a $log
-            echo $DATE 99 $backupset >> $STATUSLOG
+            echo "$DATE 99 $backupset - backup disk $BACKUPDESTDIR is not mounted" >> $STATUSLOG
             return 99
         fi
         freespace=$(df -m "$BACKUPDESTDIR" | awk "NR==2{print \$4}")
         if [[ $freespace -le $MINSPACE ]]; then
             echo "*** Backup space is running short. Only $freespace MB left on $BACKUPDESTDIR!. Exiting." | tee -a $log
-            echo $DATE 95 $backupset >> $STATUSLOG
+            echo "$DATE 95 $backupset - backup free space is under the allowed limit of $freespace MB" >> $STATUSLOG
             return 95
         fi
         # make sure the local backup folder is present (in case of the very first backup)
@@ -133,6 +133,14 @@ syntheticFullBackup() {
         # for some reason symbolic links do not work as remote arguments to the --link-dir option so we have to get it unwrapped into the folder it's pointing to
         LASTBACKUPFULLNAME=$(ssh -n $SERVER "readlink $linkdest")
         if [[ $? -eq 0 ]]; then
+            # check if it's a valid folder
+            ssh -n $SERVER "test -e $LASTBACKUPFULLNAME"
+            if [[ $? -ne 0 ]]; then
+                echo "Link to the previous backup is broken: $linkdest -> $LASTBACKUPFULLNAME" | tee -a $log
+                echo "If you wish to continue remove the broken link and the full backup will start" | tee -a $log
+                echo "$DATE 69 $backupset - error setting up a remote backup to $SERVER due to a bad symlink to the previous backup" >> $STATUSLOG
+                return
+            fi
             opts+=(--link-dest=../$(basename $LASTBACKUPFULLNAME))  # for remote systems it needs to be relative, not absolute, due to the URL addressing scheme
             #echo "*** Backing up against $LASTBACKUPFULLNAME" | tee -a $log
         fi
@@ -169,25 +177,25 @@ syntheticFullBackup() {
         # this is because rsyncd (the server side) need permissions to set group ownership to match that of the parent folder. you could change rsyncd to run as root to make it go away
         # 2. some further backups to remote systems, like TSM can't work with relative links
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "mv $linkdest.$DATE.inflight $linkdest.$DATE; ln -snf $linkdest.$DATE $linkdest; echo $DATE 0 $backupset >> $STATUSLOG"
-            echo "$DATE 0 $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "mv $linkdest.$DATE.inflight $linkdest.$DATE; ln -snf $linkdest.$DATE $linkdest; echo \"$DATE 0 $backupset - successful synthetic full backup from $backupset\" >> $STATUSLOG"
+            echo "$DATE 0 $backupset - successful synthetic full backup to $SERVER" >> $STATUSLOG
         else
             # use relative for local backups do the following:
             #ln -snf $(basename $linkdest.$DATE) $linkdest
             mv $linkdest.$DATE.inflight $linkdest.$DATE
             ln -snf $linkdest.$DATE $linkdest
-            echo "$DATE 0 $backupset" >> $STATUSLOG
+            echo "$DATE 0 $backupset - successful synthetic full local backup" >> $STATUSLOG
         fi
     else
         echo "*** $backupset $source backup for $DATE finished with $error" | tee -a $log
         echo "Errors collected during the last run from stderr:" | tee -a $log
         cat $errorlog | tee -a $log
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "mv $linkdest.$DATE.inflight $linkdest.$DATE.partial; echo $DATE $error $backupset >> $STATUSLOG"
-            echo "$DATE $error $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "mv $linkdest.$DATE.inflight $linkdest.$DATE.partial; echo \"$DATE $error $backupset - rsync error during the synthetic full backup from $backupset\" >> $STATUSLOG"
+            echo "$DATE $error $backupset - rsync error during the synthetic full backup to $SERVER" >> $STATUSLOG
         else
             mv $linkdest.$DATE.inflight $linkdest.$DATE.partial
-            echo "$DATE $error $backupset" >> $STATUSLOG
+            echo "$DATE $error $backupset - rsync error during the synthetic full local backup " >> $STATUSLOG
         fi
     fi
 }
@@ -227,20 +235,20 @@ fullBackup(){
         #  24     Partial transfer due to vanished source files - could happen due to a backup of a live system
         echo "*** Full backup for $backupset on $DATE successful" | tee -a "$log"
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "echo $DATE 0 $backupset >>$STATUSLOG"
-            echo "$DATE 0 $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "echo \"$DATE 0 $backupset - successful full backup from $backupset\" >> $STATUSLOG"
+            echo "$DATE 0 $backupset - successful full backup to $SERVER" >> $STATUSLOG
         else
-            echo $DATE 0 $backupset >>$STATUSLOG
+            echo "$DATE 0 $backupset - successful full local backup"  >>$STATUSLOG
         fi
     else
         echo "*** Full backup for $backupset on $DATE finished with error $error" | tee -a "$log"
         echo "Errors collected during the last run from stderr:" | tee -a "$log"
         cat "$errorlog" | tee -a "$log"
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "echo $DATE $error $backupset >> $STATUSLOG"
-            echo "$DATE $error $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "echo \"$DATE $error $backupset - rsync error during the full backup from $backupset\" >> $STATUSLOG"
+            echo "$DATE $error $backupset - rsync error during the full backup to $SERVER" >> $STATUSLOG
         else
-            echo "$DATE $error $backupset" >> $STATUSLOG
+            echo "$DATE $error $backupset - rsync error during the local backup" >> $STATUSLOG
         fi
     fi
 }
@@ -256,10 +264,10 @@ folderBackup() {
     error=$?
     if [[ $error -eq 0 ]]; then
         echo "*** Folder backup of $source to $dest on $DATE successful" | tee -a "$log"
-        echo "$DATE 0 $backupset" >>$STATUSLOG
+        echo "$DATE 0 $backupset - successful folder backup" >>$STATUSLOG
     else
         echo "*** Folder backup of $source to $dest on $DATE finished with error $error" | tee -a "$log"
-        echo "$DATE $error $backupset" >> $STATUSLOG
+        echo "$DATE $error $backupset - error during the folder backup" >> $STATUSLOG
         echo "Errors collected during the last run from stderr:" | tee -a "$log"
         cat "$errorlog" | tee -a "$log"
     fi
@@ -312,10 +320,10 @@ configurationBackup(){
         #  24     Partial transfer due to vanished source files - could happen due to a backup of a live system
         echo "*** Configuration backup for $system on $DATE successful" | tee -a "$log"
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "echo $DATE 0 $backupset >>$STATUSLOG"
-            echo "$DATE 0 $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "echo \"$DATE 0 $backupset - successful configuration backup from $backupset\" >> $STATUSLOG"
+            echo "$DATE 0 $backupset - successful configuration backup to $SERVER" >> $STATUSLOG
         else
-            echo $DATE 0 $backupset >>$STATUSLOG
+            echo "$DATE 0 $backupset - successful local configuration backup" >>$STATUSLOG
         fi
         rm ${filelogs[@]}
         rm $archive
@@ -323,10 +331,10 @@ configurationBackup(){
     else
         echo "*** Configuration backup for $backupset on $DATE finished with error $error" | tee -a "$log"
         if [[ -n $destURL ]]; then  # backing up to remote rsync
-            ssh -n $SERVER "echo $DATE $error $backupset >> $STATUSLOG"
-            echo "$DATE $error $backupset (sourced from $SERVER:$STATUSLOG)" >> $STATUSLOG
+            ssh -n $SERVER "echo \"$DATE $error $backupset - error during the configuration backup from $backupset\">> $STATUSLOG"
+            echo "$DATE $error $backupset - error during the configuration backup to $SERVER" >> $STATUSLOG
         else
-            echo "$DATE $error $backupset" >> $STATUSLOG
+            echo "$DATE $error $backupset - error during the local configuration backup " >> $STATUSLOG
         fi
         echo "Errors collected during the last run from stderr:" | tee -a "$log"
         cat "$errorlog" | tee -a "$log"
@@ -369,11 +377,11 @@ tsmBackup() {
                 ssh -fNM -S $SSH_CONTROL_SOCKET -L 1800:localhost:1500 -p $SSH_PORT $USER@$SERVER
                 if [[ $? -ne 0 ]]; then
                    echo "*** Server did not wake up." | tee -a $log
-                   echo $DATE 10 $SERVER >> $STATUSLOG
+                   echo "$DATE 10 $SERVER - server did not wake up" >> $STATUSLOG
                    return 10
                 fi
             else
-                echo $DATE 9 $SERVER >> $STATUSLOG
+                echo "$DATE 9 $SERVER - ssh tunnel failed" >> $STATUSLOG
                 return 9
             fi
         fi
@@ -384,10 +392,10 @@ tsmBackup() {
     error=$?
     if [[ $error -eq 0 ]]; then
         echo "*** $SERVER backup for $DATE successful" | tee -a $log
-        echo $DATE 0 $SERVER  >> $STATUSLOG
+        echo "$DATE 0 $SERVER - tsm backup done" >> $STATUSLOG
     else
         echo "*** $SERVER backup for $DATE finished with $error" | tee -a $log
-        echo $DATE $error $SERVER >> $STATUSLOG
+        echo "$DATE $error $SERVER - tsm backup error" >> $STATUSLOG
     fi
     # terminate the tunnel
     ssh -O exit -S $SSH_CONTROL_SOCKET localhost > /dev/null
